### ISSUE TITLE
How are language groups determined?

### ISSUE THREAD

**Issue by kellertuer** [oliyh/stardev-feedback#11]
Thanks for a nice overview list, I was just wondering how this list

https://stardev.io/top/repos/julia

is generated / how often it is updated? I was just curious and looking for https://github.com/JuliaManifolds/Manifolds.jl (sure not large should be somewhere far down at around 130), but it seems to not be on the list at all?

**Comment by oliyh** [comment]
Hi,

The language is determined by Github, using a library called [Linguist](https://github.com/github/linguist).

In this case, the data for the JuliaManifolds developer has been marked as archived (removing it from the rankings) because of an issue syncing with Github. I've triggered a resync, it should show up in the rankings soon: https://stardev.io/developers/JuliaManifolds
