### ISSUE TITLE
Laravel is not listed

### ISSUE THREAD

**Issue by freekmurze** [oliyh/stardev-feedback#16]
Nice project! 👍 

One of the biggest PHP organisations, Laravel, is not listed. 

It might be a good idea to add them too as the top 10 now seems incorrect.

**Comment by oliyh** [comment]
Hi,

Thanks for letting me know! It had been archived because sometimes GitHub API throws errors which are hard to distinguish from "This account doesn't exist anymore" so it was archived (and removed from the rankings).

I've refreshed it and you can now find it here: https://stardev.io/developers/laravel and it takes its place as #2 PHP https://stardev.io/languages/php :)

Cheers
