### ISSUE TITLE
Profile Location

### ISSUE THREAD

**Issue by viitoradmin** [oliyh/stardev-feedback#19]
Hello Oliver.

Great to see amazing statistics base on github records. Appreciate you for developing this app. 

I have request to recheck my organization profile - https://stardev.io/developers/vcian
it show's "Uganda" as a country instead of "India" as we are from India. 

Let me know if you need any other details to update the location.

Thanks.

**Comment by oliyh** [comment]
Hi,

Your location on Github is "303, Avdhesh House, Opposite Gurudwara, Bodakdev, Ahmedabad, Gujarat 380054, INDIA" which can't be found in [Openstreetmap](https://www.openstreetmap.org/search?query=303%2C%20Avdhesh%20House%2C%20Opposite%20Gurudwara%2C%20Bodakdev%2C%20Ahmedabad%2C%20Gujarat%20380054%2C%20INDIA#map=6/54.915/0.417) - if you can adjust it so that it OSM can find it, you should find that stardev will geocode it properly.

Cheers
