### ISSUE TITLE
504 error for developer profile

### ISSUE THREAD

**Issue by anttiviljami** [oliyh/stardev-feedback#5]
Getting a 504 error for my profile 😢

https://stardev.io/developers/anttiviljami

**Comment by oliyh** [comment]
Hi,

Thanks for letting me know, I will look into it.

Cheers

**Comment by oliyh** [comment]
Due to the number of languages you have repos in and your relative position in the ranking sets for each, it currently takes approximately 75 seconds to load your profile which exceeds the 30s timeout of the front end. I'll look into it some more to see what can be done.

**Comment by anttiviljami** [comment]
haha, my profile is too big 🥲

how about caching the page result? fine if the first request fails with a timeout if the end result is still cached for the next one

**Comment by oliyh** [comment]
Yep that's probably the simplest thing to do, thanks for the suggestion.

**Comment by oliyh** [comment]
Hi,

Your profile page now loads but is missing the rankings: https://stardev.io/developers/anttiviljami (it took a long time to load for me, but the output is now cached for 24h).

I suspect I am now hitting another timeout fetching the rankings. My instinct is that you are towards the end of some very large sets (Ruby, C, C#) which are taking a long time. I have some ideas on how to improve the speed here but will take a little while.

By the way thank you for the generous contribution, very kind of you.

Cheers,

**Comment by oliyh** [comment]
I think I've worked it out. I should be able to fix this tomorrow.

**Comment by anttiviljami** [comment]
Really appreciate the effort 🙏 Very excited to see my profile finally 😅

**Comment by oliyh** [comment]
Fixed! An interesting case. In the end:

- You had been "archived" which can happen when Github's API fails (it "fails" when a user has deleted their account too, and it's hard to distinguish)
- When you're archived you're removed from the ranking sets
- The profile page doesn't take this into account, so it traverses all the relevant ranking sets in their entirety which takes a long time

I fixed it so that it shortcuts the ranking when the user is archived, and I also triggered a resync for your profile so that you're not appearing as archived anymore.

Congrats on your profile, it looks awesome!
