### ISSUE TITLE
Incorrect location

### ISSUE THREAD

**Issue by fbiego** [oliyh/stardev-feedback#9]
Some accounts are listed under the wrong country. 
Example; 
https://stardev.io/developers/ISEE-Technology

Is listed under Kenya but it belongs to China(Southern University of Science and Technology)

**Comment by oliyh** [comment]
Hi,

Thanks for reporting this. The geocoding method only uses geopolitical administrative places, so that account's location "Southern University of Science and Technology" doesn't return anything.

Some heuristic attempts to match then attempt to geocode "Technology" which matches a village in Kenya.

The solution to this would be to include another category of places within the geocoding dataset, which will require some analysis. This particular one comes under `amenity:university`.

Cheers

**Comment by fbiego** [comment]
NB: 
Most, if not all accounts under 'technology' category don't belong to Kenya

**Comment by oliyh** [comment]
I think I've solved this but it will take me a little while to deploy

**Comment by oliyh** [comment]
Hello, this particular profile is fixed now, thanks for your patience. It may take time to update any others.
